# Generated by Django 2.2.6 on 2019-10-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('tipo', models.CharField(max_length=250)),
                ('raza', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
    ]
