# Generated by Django 2.2.6 on 2019-11-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20191101_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_tipo', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='tipo',
        ),
        migrations.AddField(
            model_name='mascota',
            name='tipo',
            field=models.ManyToManyField(to='catalog.Tipo'),
        ),
    ]
