# Generated by Django 2.2.6 on 2019-11-02 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20191101_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='tipo',
        ),
        migrations.AddField(
            model_name='mascota',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Tipo'),
        ),
    ]
