# Generated by Django 2.2.6 on 2019-11-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20191101_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(choices=[('H', 'hembra'), ('M', 'macho')], max_length=10, null=True),
        ),
    ]
